---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: ubuntu/python:3.8-20.04_stable
    pre_build_image: true
    priveleged: true
provisioner:
  name: ansible
verifier:
  name: ansible
