---
- name: Create Vector user
  user:
    name: "{{ vector_systemd_user }}"
    state: present
    shell: /bin/bash

- name: Create vector config directory
  file:
    path: /etc/vector
    state: directory
    owner: "{{ vector_systemd_user }}"
    group: "{{ vector_systemd_group }}"
    mode: "0755"

- name: Create vector data directory
  file:
    path: /var/lib/vector
    state: directory
    owner: "{{ vector_systemd_user }}"
    group: "{{ vector_systemd_group }}"
    mode: "0755"

- name: Downlaod Vector
  get_url:
    url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp/vector.tar.gz
    mode: "0644"

- name: Extract Vector
  unarchive:
    src: /tmp/vector.tar.gz
    dest: /tmp/
    remote_src: true

- name: Copy Vector binary
  copy:
    src: /tmp/vector-x86_64-unknown-linux-gnu/bin/vector
    dest: /usr/bin/vector
    mode: '0755'
    remote_src: true
    owner: "{{ vector_systemd_user }}"
    group: "{{ vector_systemd_group }}"

- name: Configure Vectore
  import_tasks: ./config.yml

- name: Ensure systemd vector service exist
  template:
    src: vector.service.j2
    dest: "/etc/systemd/system/vector.service"
    force: true
    mode: "0644"
  notify: Restart vector service
  